name: Deploy to Joule Studio

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required for requesting the JWT
      contents: read   # required for actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Joule Studio CLI
        uses: github.com/SAP/lifecycle-operation-actions-for-joule-studio/actions/setup-jl

      - name: Fetch SCI token
        id: fetch-token
        uses: github.com/SAP/lifecycle-operation-actions-for-joule-studio/actions/token-fetch@main
        with:
          sciTenantUrl: ${{ vars.SCI_TENANT_URL }}
          sciClientId: ${{ vars.SCI_CLIENT_ID }}

      - name: Build solution
        id: zip-solution
        uses: github.com/SAP/lifecycle-operation-actions-for-joule-studio/actions/build@main


      - name: Deploy solution
        uses: github.com/SAP/lifecycle-operation-actions-for-joule-studio/actions/deploy@main
        with:
          sciToken: ${{ steps.fetch-token.outputs.sciToken }}
          jouleStudioUrl: ${{ vars.JOULE_STUDIO_URL }}
          solutionZip: ${{ steps.zip-solution.outputs.solutionZip }}
